### ISSUE TITLE
clicrbs.com.br

### ISSUE THREAD

**Issue by claviola** [rbrito/easylist-ptbr#10]
Existem sites legítimos debaixo desse domínio, como o do Zero Hora: http://zh.clicrbs.com.br/rs/
O próprio "clicrbs.com.br" também é um portal de notícias.

**Comment by rbrito** [comment]
@claviola, opa! Finalmente alguém dando feedback decente! :)

Há muita coisa que está bem desorganizada. Se você tiver uns 10 minutinhos para ajudar a mover regras do arquivo "unsorted" para arquivos mais apropriados, será um imenso prazer!

Abraços,

Rogério.
