### ISSUE TITLE
A lista bloqueia também cookies, scripts e elementos css usados em paywalls como as da Folha e G1?

### ISSUE THREAD

**Issue by fabiorfreitas** [rbrito/easylist-ptbr#14]
Os elementos das paywalls são sempre ou códigos nas páginas, ou chamados para verificar cookies ou adblockers. Eu não sei exatamente como funciona, mas sei que o [Anti Adblock Killer](https://reek.github.io/anti-adblock-killer/) usa tanto um filtro de lista, quanto um script próprio então é possível que parte da funcionalidade possa ser usada na EasyList-ptBR.

**Comment by rbrito** [comment]
@fabiorfreitas, não tenho trabalhado (nem mesmo usado!) essas regras que estão aqui. A propósito, sobre as regras, quando elas estavam escritas, sim, bloqueavam essas coisas chatas.

Voltando ao repositório, imagino que eu deva removê-lo, porque estou com muitas responsabilidades e grande parte das tecnologias disponíveis mudaram e melhoraram (a começar por novos addons, como o uBlock origin).

Quem quiser pode pegar o que desejar deste repositório e fazer uma limpeza geral nas regras que estão aqui.

O melhor de todos os mundos (e o "jeito certo") seria integrar o que for pertinente às listas regionais (ou mesmo às listas gerais, se alguma coisa por lá ainda não for contemplada--o que imagino que não seja o caso) já presentes em https://kb.adguard.com/en/general/adguard-ad-filters#spanish

**Comment by fabiorfreitas** [comment]
Entendo. Agradeço as informações e o seu esforço de até agora.

Mas levando em conta que esse repositório está linkado em vários lugares, sugiro que você considere apenas arquivá-lo, ao invés de remover, assim ele torna-se disponível apenas para leitura.

**Comment by rbrito** [comment]
Certo. Apenas por curiosidade, por onde você viu lugares que fazem referências a este repositório? Quase nunca alguém veio aqui ajudar com regras ou com qualquer outra coisa...

**Comment by fabiorfreitas** [comment]
Pesquisando no Google, mas só achei posts antigos mesmo. Tinha acho que uns dois do /r/brasil e também em alguns blogs e fóruns aleatórios.
